FROM node:18

WORKDIR /app

# Cài đặt ganache-cli
RUN npm install -g ganache

# Mở port 8545 và port Render có thể cấp
EXPOSE 8545
EXPOSE 10000

# Chạy Ganache với cổng lấy từ biến môi trường PORT (mặc định 8545)
CMD ["sh", "-c", "ganache --host 0.0.0.0 --port ${PORT:-8545} --chain.networkId 1337 --database.dbPath /app/chaindata --chain.chainId 1337 --wallet.totalAccounts 10 --wallet.defaultBalance 1000 --miner.blockGasLimit 12000000 --miner.defaultGasPrice 20000000000 --server.ws true"] 