services:
  - type: web
    name: ganache-service-7809
    env: docker
    dockerfilePath: ./Dockerfile.ganache
    plan: free
    healthCheckPath: /health
    numInstances: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

  - type: web
    name: agri-tracechain-app-7809
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --workers=1
    envVars:
      - key: GANACHE_URL
        value: https://ganache-service-7809.onrender.com
      # DATABASE_URL sẽ được add thủ công sau khi tạo database 