services:
  - type: web
    name: ganache-service
    env: docker
    dockerfilePath: ./Dockerfile.ganache
    plan: free
    healthCheckPath: /
    numInstances: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

  - type: web
    name: ganache-nginx
    env: docker
    dockerfilePath: ./Dockerfile.nginx
    plan: free
    healthCheckPath: /health
    numInstances: 1
    envVars:
      - key: GANACHE_URL
        value: http://ganache-service:10000

  - type: web
    name: agri-tracechain-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --workers=1
    envVars:
      - key: GANACHE_URL
        fromService:
          type: web
          name: ganache-service
          envVarKey: RENDER_EXTERNAL_URL
      # DATABASE_URL sẽ được add thủ công sau khi tạo database 