"""add chat history

Revision ID: 6b26ab23eb9c
Revises: add_stock_status
Create Date: 2025-05-17 19:59:03.515901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b26ab23eb9c'
down_revision = 'add_stock_status'
branch_labels = None
depends_on = None


def upgrade():
    # Tạo type Enum trước
    batch_status_enum = sa.Enum('harvested', 'processing', 'shipping', 'delivered', name='batch_status_enum')
    batch_status_enum.create(op.get_bind(), checkfirst=True)
    order_status_enum = sa.Enum('pending', 'confirmed', 'shipped', 'delivered', 'cancelled', name='order_status_enum')
    order_status_enum.create(op.get_bind(), checkfirst=True)
    user_role_enum = sa.Enum('admin', 'farmer', 'buyer', name='user_role_enum')
    user_role_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_user', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('batches', schema=None) as batch_op:
        # 1. Xóa default cũ
        batch_op.alter_column('status', server_default=None)
        # 2. Đổi kiểu cột
        batch_op.alter_column(
            'status',
            existing_type=sa.VARCHAR(length=20),
            type_=sa.Enum('harvested', 'processing', 'shipping', 'delivered', name='batch_status_enum'),
            existing_nullable=True,
            postgresql_using="status::batch_status_enum"
        )
        # 3. Đặt lại default mới
        batch_op.alter_column(
            'status',
            server_default=sa.text("'harvested'::batch_status_enum")
        )

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.alter_column('unit_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('subtotal',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        # 1. Xóa default cũ
        batch_op.alter_column('status', server_default=None)
        # 2. Đổi kiểu cột
        batch_op.alter_column(
            'status',
            existing_type=sa.VARCHAR(length=20),
            type_=sa.Enum('pending', 'confirmed', 'shipped', 'delivered', 'cancelled', name='order_status_enum'),
            existing_nullable=True,
            postgresql_using="status::order_status_enum"
        )
        # 3. Đặt lại default mới
        batch_op.alter_column(
            'status',
            server_default=sa.text("'pending'::order_status_enum")
        )

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('transaction_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('stock_status')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('trace_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address', sa.String(length=50), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        # 1. Xóa default cũ (nếu có)
        batch_op.alter_column('role', server_default=None)
        # 2. Đổi kiểu cột
        batch_op.alter_column(
            'role',
            existing_type=sa.VARCHAR(length=10),
            type_=sa.Enum('admin', 'farmer', 'buyer', name='user_role_enum'),
            existing_nullable=False,
            postgresql_using="role::user_role_enum"
        )
        # 3. Đặt lại default mới (nếu muốn, ví dụ mặc định là 'buyer')
        # batch_op.alter_column('role', server_default=sa.text("'buyer'::user_role_enum"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('admin', 'farmer', 'buyer', name='user_role_enum'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    with op.batch_alter_table('trace_logs', schema=None) as batch_op:
        batch_op.drop_column('ip_address')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_status', sa.VARCHAR(length=20), server_default=sa.text("'in_stock'::character varying"), autoincrement=False, nullable=False))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
        batch_op.alter_column('transaction_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('pending', 'confirmed', 'shipped', 'delivered', 'cancelled', name='order_status_enum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.alter_column('subtotal',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('unit_price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('harvested', 'processing', 'shipping', 'delivered', name='batch_status_enum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'harvested'::character varying"))

    op.drop_table('reports')
    op.drop_table('chat_history')
    # Xóa type Enum sau cùng
    user_role_enum = sa.Enum('admin', 'farmer', 'buyer', name='user_role_enum')
    user_role_enum.drop(op.get_bind(), checkfirst=True)
    order_status_enum = sa.Enum('pending', 'confirmed', 'shipped', 'delivered', 'cancelled', name='order_status_enum')
    order_status_enum.drop(op.get_bind(), checkfirst=True)
    batch_status_enum = sa.Enum('harvested', 'processing', 'shipping', 'delivered', name='batch_status_enum')
    batch_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
